---
- hosts: all
  become: true
  become_user: rizqirazkafi

  tasks:
    - name: install packages
      package:
        name:
          - hello
          - neovim
          - tmux
          - vim
          - wget
          - git
          - htop
          - ranger
          - xclip
          - ripgrep
          - cargo
          - python3-pip
          - python3-venv
          - npm
    - name: create directory for config 
      ansible.builtin.file:
        path: /home/rizqirazkafi/.config
        state: directory
        owner: rizqirazkafi
        group: rizqirazkafi
        mode: '0775'
    - name: Copy neovim config 
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: nvim
        dest: /home/rizqirazkafi/.config
    - name: change ownership recursively
      ansible.builtin.file:
        path: /home/rizqirazkafi/.config
        state: directory
        recurse: yes
        owner: rizqirazkafi
        group: rizqirazkafi
        mode: '0775'
    - name: copy tpm
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: .tmux
        dest: /home/rizqirazkafi/.tmux
    - name: copy .tmux.conf
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: .tmux.conf
        dest: /home/rizqirazkafi/.tmux.conf
    - name: change owner of .tmux.conf
      ansible.builtin.file:
        path: /home/rizqirazkafi/.tmux.conf
        owner: rizqirazkafi
        group: rizqirazkafi
        mode: '0775'
    - name: change owner of .tmux
      ansible.builtin.file:
        path: /home/rizqirazkafi/.tmux
        recurse: yes
        owner: rizqirazkafi
        group: rizqirazkafi
        mode: '0775'



