---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: install packages
      package:
        name:
          - hello
          - neovim
          - tmux
          - vim
          - wget
          - git
          - htop
          - ranger
          - xclip
          - ripgrep
          - cargo
          - python3-pip
          - python3-venv
          - npm
          - nginx
          - php-fpm
    - name: copy motd
      ansible.builtin.copy:
        src: motd
        dest: /etc/motd
    - name: copy sshd_config
      ansible.builtin.copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
    - name: enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
    - name: enable php-fpm
      ansible.builtin.service:
        name: php8.3-fpm
        state: started

- hosts: all
  become: true
  become_user: rizqirazkafi

  tasks:
    - name: Copy neovim config 
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: nvim
        dest: /home/rizqirazkafi/.config
    - name: copy tpm
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: .tmux
        dest: /home/rizqirazkafi/.tmux
    - name: copy .tmux.conf
      ansible.posix.synchronize:
        private_key: ~/.ssh/id_ed25519
        src: .tmux.conf
        dest: /home/rizqirazkafi/.tmux.conf
    - name: copy .bashrc
      ansible.posix.synchronize:
        src: .bashrc
        dest: /home/rizqirazkafi/.bashrc
    - name: copy ssh authorized_keys
      ansible.posix.synchronize:
        src: authorized_keys
        dest: /home/rizqirazkafi/.ssh/authorized_keys

